namespace SSHC.Generator
{
    internal record AutogenerationMethodInformation(
        string MethodName,
        AutogeneratedMethodType Type,
        Dictionary<Type, string> ParametersMetaData, 
        Type ReturnType);
}
