using Microsoft.AspNetCore.Mvc;
using Simons.Generators.HttpClient.Collection.Methods;
using Simons.Generators.HttpClient.Tracing;
using System.Diagnostics;
using System.Reflection;

namespace Simons.Generators.HttpClient.Collection
{
    internal static class ControllerInformationCollector
    {
        private const string TEMPLATE_CONTROLLER = "[controller]";
        private const string ROUTE_CONTROLLER = "Controller";

        public static IEnumerable<AutogenerationInformation?> Collect(Assembly assembly, GeneratorArguments args, GeneratorTrace trace)
        {
            var types = GetAutoGeneratedControllerTypes(assembly);
            if (args.Verbose) { trace.Add($"Assembly contains {types.Count()} types to generate for"); }

            foreach (var type in types)
            {
                yield return CollectController(type, args);
            }
        }

        private static AutogenerationInformation? CollectController(Type type, GeneratorArguments args)
        {
            AutogenerationInformation info = MakeInfo(type);
            if (args.AreNullReturnsAllowed) { info.AreNullReturnsAllowed = true; }
            if (!IsValidAnnotatedApiController(type))
            {
                info.AutogenerationResult = AutogenerationResult.Failure;
                info.Reason = $"{type.Name} is not an AspNetCore.ApiController";
                return info;
            }

            info.Methods = CollectMethods(type, info).ToList();
            return info;
        }

        private static IEnumerable<AutogenerationMethodInformation> CollectMethods(Type type, AutogenerationInformation info)
        {
            foreach (var method in GetAllApiMethodsFromController(type))
            {
                var methodInfo = new AutogenerationMethodInformation(
                    GetControllerMethodName(method),
                    GetControllerMethodType(method),
                    GetControllerMethodParameters(method),
                    GetPostFromBodyParameterIndex(method),
                    GetControllerMethodReturnType(method),
                    info.AreNullReturnsAllowed
                );

                yield return methodInfo;
            }
        }

        public static IEnumerable<Type> GetAutoGeneratedControllerTypes(Assembly assembly)
        {
            foreach (Type type in assembly.GetTypes())
            {
                if (type.IsDefined(typeof(AutoGenerateApiClientAttribute)))
                {
                    yield return type;
                }
            }
        }

        public static AutogenerationInformation MakeInfo(Type type)
            => new(type, type.Name, GetControllerRoute(type));

        private static bool IsValidAnnotatedApiController(Type autogeneratableType)
        {
            bool isApiController = autogeneratableType.IsDefined(typeof(ApiControllerAttribute));
            bool hasRoute = autogeneratableType.IsDefined(typeof(RouteAttribute));

            return isApiController && hasRoute;
        }

        private static string GetControllerRoute(Type controllerType)
        {
            string template = controllerType.GetCustomAttribute<RouteAttribute>()!.Template;
            return ParseRouteTemplate(controllerType, template);
        }

        private static string ParseRouteTemplate(Type controllerType, string template)
        {
            var controllerName = template.Split("/")[0];
            if (controllerName == TEMPLATE_CONTROLLER)
            {
                controllerName = controllerType.Name.Replace(ROUTE_CONTROLLER, "");
            }

            return controllerName;
        }

        private static IEnumerable<MethodInfo> GetAllApiMethodsFromController(Type controllerType)
            => controllerType.GetMethods().Where(IsValidAnnotatedApiMethod);



        private static bool IsValidAnnotatedApiMethod(MethodInfo method)
        {
            bool valid =
                method.IsDefined(typeof(HttpGetAttribute)) ||
                method.IsDefined(typeof(HttpPostAttribute));

            valid &= method.IsDefined(typeof(ReturnsAttribute));

            return valid;
        }

        private static string GetControllerMethodName(MethodInfo controllerMethod)
        {
            //if method has a different name in its attribute, return that one instead
            var get = controllerMethod.GetCustomAttribute<HttpGetAttribute>();
            var post = controllerMethod.GetCustomAttribute<HttpPostAttribute>();

            if (get is not null && !string.IsNullOrEmpty(get.Template)) { return get.Template; }
            else if (post is not null && !string.IsNullOrEmpty(post.Template)) { return post.Template; }

            return controllerMethod.Name; //never gets here
        }

        private static AutogeneratedMethodType GetControllerMethodType(MethodInfo controllerMethod)
        {
            if (controllerMethod.IsDefined(typeof(HttpGetAttribute))) { return AutogeneratedMethodType.GET; }
            else if (controllerMethod.IsDefined(typeof(HttpPostAttribute))) { return AutogeneratedMethodType.POST; }
            else return AutogeneratedMethodType.ERROR;
        }

        private static List<(Type Type, string Name)> GetControllerMethodParameters(MethodInfo controllerMethod)
        {
            var parameters = controllerMethod.GetParameters().Where(p =>
                p.IsDefined(typeof(FromQueryAttribute)) ||
                p.IsDefined(typeof(FromBodyAttribute))
            );

            if (!parameters.Any()) { return new(); }

            var paramDict = new List<(Type Type, string Name)>();
            foreach (var param in parameters.Where(p => !string.IsNullOrEmpty(p.Name)))
            {
                paramDict.Add((param.ParameterType, param.Name!));
            }

            return paramDict;
        }

        private static int GetPostFromBodyParameterIndex(MethodInfo controllerMethod)
        {
            var fromBody = controllerMethod.GetParameters().Where(p =>
                p.IsDefined(typeof(FromBodyAttribute))
            ).FirstOrDefault();

            if (fromBody == null) { return -1; }
            return controllerMethod.GetParameters().ToList().IndexOf(fromBody);
        }

        private static Type GetControllerMethodReturnType(MethodInfo controllerMethod)
        {
            var returns = controllerMethod.GetCustomAttribute<ReturnsAttribute>();
            return returns!.ReturnType;
        }
    }
}
