using Simons.Generators.HttpClient.Collection;
using Simons.Generators.HttpClient.Collection.Methods;
using Simons.Generators.HttpClient.Helpers;

namespace Simons.Generators.HttpClient
{
    internal class FormattingClassGenerator
    {
        private AutogenerationCodeContainer _container = new();
        public FormattingClassGenerator AddUsings(IEnumerable<string> usings)
        {
            _container.AddUsings(usings);
            return this;
        }

        public FormattingClassGenerator AddNamespace(string nameSpace)
        {
            _container.SetNamespace($"namespace {nameSpace}");
            return this;
        }

        public FormattingClassGenerator AddClass(AutogenerationInformation classInfo)
        {
            _container.SetClassDefinition($"public{(classInfo.GenerateAsPartial ? " partial" : "")} class {classInfo.ControllerRoute}ApiClient : ApiClient");
            return this;
        }

        public FormattingClassGenerator AddGetOnlyProperty(Type returnValue, string propertyName, string propertyValue)
        {
            _container.AddPublicPropertyDefintion($"public {SwapPrimitive(returnValue)} {propertyName} => \"{propertyValue}\";");
            return this;
        }

        public FormattingClassGenerator AddPublicMethod(AutogenerationMethodInformation methodInfo)
        {
            _container.AddPublicMethodDefinition(
                MakeMethodDefinition(methodInfo),
                MakeMethodBody(methodInfo)
            );

            return this;
        }

        public string Generate()
            => _container.ToString();

        private static string MakeMethodDefinition(AutogenerationMethodInformation methodInfo)
        {
                return $"public Task{TaskSnippetFromMethodReturnAnnotation(methodInfo)} {methodInfo.MethodName}" +
                       $"({string.Join(", ", methodInfo.ParametersMetaData.Select(tuple => $"{SwapPrimitive(tuple.Type)} {tuple.Name}"))}) ";
        }

        private static List<string> MakeMethodBody(AutogenerationMethodInformation methodInfo) => methodInfo.Type switch
        {
            AutogeneratedMethodType.GET => MakeGetMethodBody(methodInfo), 
            AutogeneratedMethodType.POST => MakePostMethodBody(methodInfo),
            _ => new()
        };

        private static List<string> MakeGetMethodBody(AutogenerationMethodInformation methodInfo)
            => GetMethodBody.Create(methodInfo).ToString();
        
        private static List<string> MakePostMethodBody(AutogenerationMethodInformation methodInfo)
            => PostMethodBody.Create(methodInfo).ToString();

        private static string SwapPrimitive(Type type)
            => TypeHelper.TypeAsCodeSnippet(type);

        private static string TaskSnippetFromMethodReturnAnnotation(AutogenerationMethodInformation methodInfo)
        {
            if (methodInfo.AreNullReturnsAllowed)
            {
                return methodInfo.ReturnType != typeof(void) ? $"<{SwapPrimitive(methodInfo.ReturnType)}?>" : "";
            }
            else
            {
                return methodInfo.ReturnType != typeof(void) ? $"<{SwapPrimitive(methodInfo.ReturnType)}>" : "";
            }
        }
    }
}
