namespace Simons.Generators.ApiClient.Collection.Methods
{
    internal record AutogenerationMethodInformation
    {
        public AutogenerationMethodInformation(
            string methodName,
            AutogeneratedMethodType type,
            List<(Type Type, string Name)> parametersMetaData,
            int fromBodyIndex,
            Type returnType,
            bool allowNullReturns = false)
        {
            MethodName = methodName;
            Type = type;
            FromBodyIndex = fromBodyIndex;
            ReturnType = returnType;
            AreNullReturnsAllowed = allowNullReturns;
            //this block "sorts" the dictionary to make access of the frombody element much easiert
            if (fromBodyIndex > 0)
            {
                var elem = parametersMetaData.ElementAt(fromBodyIndex);
                _ = parametersMetaData.Remove(elem);
                ParametersMetaData = parametersMetaData;
                ParametersMetaData.Add((elem.Type, elem.Name));
            }
            else
            {
                ParametersMetaData = parametersMetaData;
            }
        }

        public string MethodName { get; init; }
        public AutogeneratedMethodType Type { get; init; }
        public List<(Type Type, string Name)> ParametersMetaData { get; init; }
        public int FromBodyIndex { get; init; }
        public Type ReturnType { get; init; }
        public bool AreNullReturnsAllowed { get; init; }
    }


}
